
# -*- coding: utf-8 -*-
messages = {
u'notice-ie6': '<p><strong>This website doesn\'t support Internet Explorer 6.</strong> It doesn\'t support IE7 and IE8 either, but they work well in most cases.</p><p><strong>Modern web browsers are recommended.</strong> This includes <a href="http://getfirefox.com/">Mozilla Firefox 3.5+</a>, Google Chrome, Safari 4+ and so on. If the score board doesn\'t look like <a href="/images/screenshot-firefox.png">this image</a> the chances are that it is not.</p>',
u'notice-help': '<p>NOTICE: This site needs your help.</p><p>Any web programmer or designer will be helpful for enhanced service.</p>',

u'select_user': 'Select User',
u'navigation_without_alias': 'You will see other menus here once you have selected the alias above. Enroll a new one below if you do not have.<br />You may choose the alias the same as the friend ID too (as like Jubegraph).',

u'enroll_help': "'Alias' is internal name to use our service. This is used for JubeatInfo only. 'Friend ID' is personal key of konami service. You can find it on e-amusement service.",

u'ripples-app-desc': 'iPhone JubeatInfo app',
u'knit-service-beta-desc': 'Services currently available as BETA:',
u'knit-service-developing-desc': 'Services under development:',
u'knit-free-desc': 'Browse information without konami membership.',
u'knit-massda-desc': 'Download files for jubegraph update.',
u'knit-humanreadable-desc': 'You can browse your play data as a human-readable format.',
u'knit-statistics-desc': 'You can also browse your play statistics and analyze it.',
u'knit-statistics-adv-desc': 'You can analyze play data with advanced user interface, with more organized way and with plenty data.',
u'knit-mobileweb-desc': 'Mobile website',
u'knit-iphoneapp-desc': 'Full support for iPhone `JubeatInfo` app (currently available partially)',
u'policy': 'Service Policy:',
u'policy-update': 'Update Interval: 24+ hours later after last update without request / in 30 minutes after update request (except 05h-08h)',
u'policy-update-notice': 'Your data will be updated in next minor update time. See our policy about minor update interval.',
u'policy-unstable': 'Service is unstable yet. Service temporarilly can be unavailable or lost data without notice.',
u'policy-deny': 'You should set konami account to publish your information. if not, our service deactivate auto-update of your account. To activate your account again, set konami account to publish your information and click "Request Update"',

u'faq-user-from-japan-question': 'Why not users in Japan?',
u'faq-user-from-japan-answer': 'You can buy e-AMUSEMENT PASS in Japan. Please use Jubegraph rather than JubeatInfo, if available.',
u'faq-more-information-question': 'Why don\' you provide more informations? (like Play Count, No Gray, All Yellow, Full combo etc)',
u'faq-more-information-answer': 'We have technical limitation to aggregate play data. We do not hide any collected or collectable informations. We cannot do more.',

u'disclaimer': 'Disclaimer: 3rddev supports this service on behalf of JubeatInfo team. Every rights, duty and legal responsibility is held by JubeatInfo team. Neither 3rddev nor JubeatInfo team are legally responsible for the use of this service by users in Japan. Use at your own risk if you are in Japan.',
u'user-agreement': 'User agreement: Every user should pray new record of developer team whenever using this service :p',
u'support': 'Support',

u'enroll-success': 'You are enrolled to JubeatInfo service.',
u'request-accepted': 'Your update request is Accepted.',

u'alias': 'Alias',
u'enroll': 'Enroll',
u'main_page': 'Main Page',
u'request_update': 'Update Request',
u'average_score': 'Average Score',
u'statistics-tbs': 'TBS Ranking',
u'my_page': 'Show data',
u'toolbox': 'Toolbox',

u'difftool': 'Diff Tool',
u'no_compare': 'Compare to the user average',
u'compare_rival': 'Compare to the other user',
u'swap_rival': 'See this page at the view of this user',
u'compare_date': 'Compare between two dates',
u'before-date': 'Before',
u'after-date': 'After',
u'now-date': 'NOW',
u'diff': 'Diff',

u'statistics': 'Statistics',
u'grade_bsc': 'BSC',
u'grade_adv': 'ADV',
u'grade_ext': 'EXT',
u'grade_tot': 'TOT',

u'scoreboard': 'Score Board',
u'scoremode': 'Score Display',
u'raw_score': 'Raw',
u'raw_score_from_exc': 'Minus 1,000,000',
u'scaled_score': 'Scaled',
u'scaled_score_desc': 'The "scaled" score shows the combined number of GREATs, GOODs or MISSes you have made. 0.0 means EXCELLENT; when the gauge is full each GREAT, GOOD and MISS costs 0.3, 0.6 and 1.0 points respectively. (Thus the scaled score is usually negative.) The scaled score is approximate and does not have a clear meaning when the gauge was not full.',
u'tracktitle': 'Title',
u'order-version': 'Version and display order',
u'order-title': 'Title only',
u'order-sort_id': 'Display order',
u'order-score': 'Score',
u'order-level': 'Level',
u'order-notes': '#Notes',
u'order-date': 'Date',
u'order-diff': 'Diff',
u'icon_avg': 'AVG',
u'icon_rival': 'Rival',
u'notes': '#Notes: ',
u'title-average': 'Average',
u'title-total': 'Total',
u'rival-summary': 'Versus Rival',
u'emphasis-win': 'WIN!',
u'emphasis-draw': 'DRAW',
u'emphasis-new': 'NEW!',

u'rank': 'Rank',
u'userstat': 'User Statistics',
u'as-of-%s': 'As of %s',
u'friend_id': 'Friend ID',
u'card_name': 'Card name',
u'title': 'Title',
u'group_name': 'Group',
u'no-group': 'No group',
u'last_play': 'Last play',
u'last_location': 'Last play location',
u'last_date': 'Last play date',
u'jubility': 'Jubility',
u'jubility_diff_short': 'diff',
u'achievement_point': 'Achievement point',
u'achievement_rank': 'Achievement point rank',
u'play_count': 'Play Count',
u'clear_count': 'Clear Count',
u'save_count': 'Save Count',
u'saved_count': 'Saved Count',
u'play_count_short': 'Play',
u'clear_count_short': 'Clear',
u'save_count_short': 'Save',
u'saved_count_short': 'Saved',
u'excellent': 'Excellent',
u'excellent_count': 'Excellent Count',
u'excellent_tune_count': 'Excellent tunes Count',
u'fullcombo': 'Full-combo',
u'fullcombo_count': 'Full-combo count',
u'fullcombo_tune_count': 'Full-combo tunes count',
u'counts': 'Counts',
u'tunes': 'Tunes',
u'matched_player_count': 'Matched player count',
u'matched_victory_count': 'Match victory count',
u'matched_player_count_short': 'Matched',
u'matched_victory_count_short': 'Victory',
u'marker': 'Marker',
u'background': 'Background',
u'timestamp': 'Update time',
u'addiction': 'Addiction Level',

u'clear_rate': 'Clear Rate',
u'fullcombo_rate': 'Fullcombo Rate',
u'excellent_rate': 'Excellent Rate',
u'effective_excellent_rate': 'Effective Excellent Rate',
u'saved_rate': 'SAVED Rate',
u'matched_player_rate': 'Matched Player Rate',
u'matched_victory_rate': 'Match Victory rate',
u'matched_victory_percent': 'Victory Rate',
u'addiction_rate': 'Addiction Level',
u'concentration_degree': 'Concentration Level',
u'efficiency_degree': 'Efficiency Level',

u'tbs-user-count': '%d Total Users',

u'Toolbox': 'Toolbox',
u'raw-files': 'Raw Data Files',
u'raw-main': 'Main',
u'raw-score': 'Score',
u'raw-warning': 'Use at your own risk.',
u'raw-warning-jubegraph': 'While these files can be used for %s, we do not guarantee that Jubegraph will parse and process them correctly.',
u'raw-warning-recommendation': 'It is best to use your own E-Amusement Pass to get them instead.',
u'Jubegraph': 'Jubegraph',

u'err_hint': 'There may be hint about this error:',
u'err_http_404': 'This is not the web page you are looking for.',
u'err_http_405': 'This is not accessible with given method.',
u'err_http_500': 'Server cannot serve your current request.',

u'err_no_alias': 'No given alias.',
u'err_invalid_alias': 'Given alias is not enrolled to JubeatInfo service. Try valid one or enroll to JubeatInfo Service.',

u'err_enroll_no_friend_id': 'You should input a friend id. You can find your one on e-amusement website.',
u'err_enroll_friend_id_knit': 'This friend id is not seem to valid Jubeat Knit friend id. Try again with valid one.',
u'err_enroll_duplicate': 'Alias or Friend ID you input is already enrolled.',
u'err_enroll_duplicated_friend_id': 'Given Friend ID is already enrolled. Find your alias rather than trying enrollment.',
u'err_enroll_duplicated_alias': 'Given Alias is already enrolled for other Friend ID.',

u'err_request_no_alias': 'No given alias. You should input an alias to be bound to your friend id.',
u'err_request_update_average': 'You cannot request update for System user.',

u'err_data_not_collected': 'JubeatInfo did not collected your data yet. Please wait next minor update time slot.',
u'err_eamusement_system': 'JubeatInfo meets e-AMUSEMENT system error. It usually caused by wrong Friend ID. If not, click request update button and wait next update.',
u'err_eamusement_nonpublic': 'You did not set your e-AMUSEMENT PASS as public yet. Please set it public and click request update button.',
}
contents = {
# markers
u'ニット': 'Knit',
u'サイバー': 'Cyber',
u'フラワー': 'Flower',
u'アフロ': 'Afro',
u'シャッター': 'Shutter',
u'ブルーリング': 'Blue Ring',
u'花火': 'Fireworks',
u'ターゲット': 'Target',
u'たまご': 'Egg',
u'火山': 'Volcano',
u'ゲージ': 'Gage',
u'オコジョ': 'Stoat',
u'アイス': 'Ice',
u'シャボン玉': 'Bubble',
u'デジタルブロック': 'Digital Block',
u'サンドアート': 'Sand Art',
u'ミラーボール': 'Mirror Ball',
u'リプルズ': 'Ripples',
#$__l10n['ユビ子': 
u'触': 'Touch',
u'バナナ': 'Banana',
#$__l10n['ブラー': 
u'絵画': 'Painting',
u'トーラス': 'Torus',
u'襖': 'Sliding', # Sliding Door
u'ステルス': 'Stealth',
#$__l10n['色彩構成': ''; // Color construction
u'ねんごろねこ': 'Polite Cat',
u'ストップウォッチ': 'Stop Watch',
u'コンシェルジュ': 'Concierge',
#$__l10n['jubeatくん': 'Jubeat',

# backgrounds
u'グリーン': 'Green',
u'ブルー': 'Blue',
u'レモン': 'Lemon',
u'ダーク': 'Dark',

# locations
u'愛知県': 'Aichi, Japan',
u'秋田県': 'Akita, Japan',
u'青森県': 'Aomori, Japan',
u'千葉県': 'Chiba, Japan',
u'愛媛県': 'Ehime, Japan',
u'福井県': 'Fukui, Japan',
u'福岡県': 'Fukuoka, Japan',
u'福島県': 'Fukushima, Japan',
u'岐阜県': 'Gifu, Japan',
u'群馬県': 'Gunma, Japan',
u'広島県': 'Hiroshima, Japan',
u'北海道': 'Hokkaido, Japan',
u'香港': 'Hong Kong',
u'兵庫県': 'Hyogo, Japan',
u'茨城県': 'Ibaraki, Japan',
u'石川県': 'Ishikawa, Japan',
u'岩手県': 'Iwate, Japan',
u'香川県': 'Kagawa, Japan',
u'鹿児島県': 'Kagoshima, Japan',
u'神奈川県': 'Kanagawa, Japan',
u'高知県': 'Kochi, Japan',
u'大韓民国': 'Korea',
u'대한민국': 'Korea',
u'熊本県': 'Kumamoto, Japan',
u'京都府': 'Kyoto, Japan',
u'三重県': 'Mie, Japan',
u'宮城県': 'Miyagi, Japan',
u'宮崎県': 'Miyazaki, Japan',
u'未設定': 'N/A',
u'長野県': 'Nagano, Japan',
u'長崎県': 'Nagasaki, Japan',
u'奈良県': 'Nara, Japan',
u'新潟県': 'Niigata, Japan',
u'大分県': 'Oita, Japan',
u'岡山県': 'Okayama, Japan',
u'沖縄県': 'Okinawa, Japan',
u'大阪府': 'Osaka, Japan',
u'佐賀県': 'Saga, Japan',
u'埼玉県': 'Saitama, Japan',
u'滋賀県': 'Shiga, Japan',
u'静岡県': 'Shizuoka, Japan',
u'台湾': 'Taiwan',
u'栃木県': 'Tochigi, Japan',
u'徳島県': 'Tokushima, Japan',
u'東京都': 'Tokyo, Japan',
u'鳥取県': 'Tottori, Japan',
u'富山県': 'Toyama, Japan',
u'和歌山県': 'Wakayama, Japan',
u'山形県': 'Yamagata, Japan',
u'山口県': 'Yamaguchi, Japan',
u'山梨県': 'Yamanashi, Japan',
u'シンガポール': 'Singapore',
u'マカオ': 'Macau',
}
