
# -*- coding: utf-8 -*-
messages = {
u'notice-ie6': '<p><strong>이 사이트는 인터넷 익스플로러 6을 지원하지 않습니다.</strong> IE7이나 IE8은 완전하지는 않지만 대부분은 정상적으로 표시합니다.</p><p><strong>좀 더 "잘" 만든 브라우저를 사용해 주세요.</strong> 여기에는 <a href="http://getfirefox.com">모질라 파이어폭스 3.6+</a>, 구글 크롬, 사파리 4+ 등이 포함됩니다. 점수 표가 <a href="/images/screenshot-firefox.png">이 그림</a>과 같이 보이면 됩니다.</p>',
u'notice-help': '<p>이 사이트는 도움이 필요합니다.</p><p>웹 프로그램이나 웹 디자인을 할 줄 아는 분이 도와주시면 더욱 편리하고 깔끔한 사이트가 될 수 있습니다.</p>',

u'select': '선택',
u'select_user': '사용자 선택',
u'navigation_without_alias': '사용자 선택 후 개인 메뉴가 활성화됩니다. 등록하지 않았다면 아래에서 등록해 주세요.<br />마쓰다와 동일한 방법으로 사용하시려면 둘 모두 프렌드 아이디를 넣어주세요.',

u'enroll_help': "'이름'은 유비트인포 사이트 내부에서 사용하는 이름입니다. 등록 이후에는 항상 '이름'으로 정보를 조회하실 수 있습니다. '프렌드ID'는 코나미에서 제공하는 개인 식별 번호입니다. 이어뮤즈 서비스에서 확인하실 수 있습니다.",

u'ripples-app-desc': '아이폰 JubeatInfo 앱',
u'knit-service-beta-desc': '테스트 중인 서비스',
u'knit-service-developing-desc': '개발 중인 서비스',
u'knit-massda-desc': '마쓰다 갱신용 파일 다운로드',
u'knit-humanreadable-desc': '플레이 자료를 읽기 쉬운 포맷으로 제공',
u'knit-statistics-desc': '플레이 자료의 통계를 추적하고 분석',
u'knit-statistics-adv-desc': '보다 다양한 플레이 자료 분석을 더 편리한 인터페이스로 제공',
u'knit-mobileweb-desc': '모바일 웹',
u'knit-iphoneapp-desc': '아이폰 JubeatInfo 앱 (일부 기능만 가능)',
u'policy': '운영 정책',
u'policy-update': '갱신 간격: 갱신 요청이 없을 경우 마지막 갱신 후 24+시간 이후 / 갱신 요청이 있을 경우 30분 이내 (05-08시 제외)',
u'policy-update-notice': '다음 갱신 주기에 데이터가 갱신됩니다. 갱신 주기는 정책을 참고하세요.',
u'policy-unstable': '서비스가 아직 불안정합니다. 예고 없이 서비스가 일시 중지되거나 자료가 사라질 수 있습니다.',
u'policy-deny': '서비스는 계정을 "정보 공개"로 설정해 두셔야만 사용하실 수 있습니다. "정보 공개"로 설정되지 않은 계정은 자동으로 비활성화되며 자동 갱신 대상에서 제외됩니다. 다시 자동 갱신 목록에 포함하시려면 계정을 "정보 공개"로 설정하고 "갱신 요청"을 클릭해 주세요.',

u'FAQ': '자주 묻는 질문',
u'faq-user-from-japan-question': '왜 일본 거주자는 이용할 수 없나요?',
u'faq-user-from-japan-answer': '일본 거주자는 e-AMUSEMENT PASS를 구입하실 수 있습니다. e-AMUSEMENT PASS 결제 후 Jubegraph를 이용해 주세요.',
u'faq-more-information-question': '더 많은 정보를 제공해주세요. (노 그레이, 올 옐로, 풀 콤보 등)',
u'faq-more-information-answer': '기술적인 한계로 추가 데이터 수집이 불가능합니다. 현재 수집 가능한 모든 데이터를 수집하여 제공하고 있습니다.',

u'disclaimer': '면책 조항: 3rddev는 JubeatInfo 팀을 위해 서비스를 운영합니다. 모든 권리 및 의무는 JubeatInfo 팀이 보유합니다. 일본에 거주하는 사람은 이 서비스를 이용할 수 없으며, 일본에 거주하는 사용자는 이 서비스를 사용하는데 따르는 모든 법적 책임을 스스로 집니다.',
u'user-agreement': '사용자 의무: 이 서비스를 이용하는 모든 사용자는 매 이용 시마다 개발팀의 기록 갱신을 기원해야 합니다. ^^;',
u'support': '고객지원',

u'enroll-success': 'JubeatInfo 서비스에 등록하셨습니다.',
u'request-accepted': '갱신 요청을 받았습니다.',

#terms
u'alias': '이름',
u'enroll': '등록',
u'main_page': '정보 보기',
u'request_update': '갱신 요청',
u'average_score': '평균 점수 보기',
u'statistics-tbs': 'TBS 순위',
u'my_page': '내 정보 보기',
u'toolbox': '추가 기능',

u'music-total': '합산 점수',
u'music-average': '평균 점수',

u'difftool': '비교 도구',
u'no_compare': '평균과 비교하기',
u'compare_rival': '다른 사용자와 비교',
u'swap_rival': '현재 비교 중인 사용자 쪽에서 보기',
u'compare_date': '특정 날짜와 비교',
u'before-date': '이전',
u'after-date': '다음',
u'now-date': '현재',
u'diff': '비교',

u'statistics': '통계',
u'grade_bsc': 'BSC',
u'grade_adv': 'ADV',
u'grade_ext': 'EXT',
u'grade_tot': 'TOT',

u'scoreboard': '곡별 점수',
u'scoremode': '점수 표시 방법',
u'raw_score': '원 점수',
u'raw_score_from_exc': 'EXCELLENT까지 남은 점수',
u'scaled_score': '환산 점수',
u'scaled_score_desc': 'EXCELLENT까지 남은 점수를 좀 더 보기 쉽게 환산한 것입니다. 0.0이 EXCELLENT이며, 풀 게이지를 달성했을 경우 그레이트/굿/미스 시 감점은 각각 0.3/0.6/1.0점으로 환산됩니다. 풀 게이지로 클리어하지 못 했을 경우 숫자가 간단하게 떨어지지 않으므로 참고용으로만 쓰십시오.',
u'tracktitle': '제목',
u'order-version': '버전+게임 내 순서',
u'order-title': '제목',
u'order-sort_id': '게임 내 순서',
u'order-score': '점수',
u'order-level': '레벨',
u'order-notes': '노트수',
u'order-date': '갱신일',
u'order-diff': '차이',
u'icon_avg': '평균',
u'icon_rival': '상대',
u'notes': '노트 수',
u'title-average': '평균',
u'title-total': '합산',
u'rival-summary': '상대와의 전적',
u'emphasis-win': '승리!',
u'emphasis-draw': '동점',
u'emphasis-new': '갱신!',

u'rank': '순위',
u'userstat': '기본 정보',
u'as-of-%s': '%s 현재',
u'friend_id': '프렌드 ID',
u'card_name': '카드 이름',
u'title': '칭호',
u'group_name': '그룹',
u'no-group': '무소속',
u'last_play': '마지막 플레이',
u'last_location': '마지막 플레이 지역',
u'last_date': '마지막 플레이 날짜',
u'jubility': '유빌리티',
u'jubility_diff_short': '전날과 차이',
u'achievement_point': '성과 점수',
u'achievement_rank': '성과 점수 순위',
u'play_count': '플레이 횟수',
u'clear_count': '클리어 횟수',
u'save_count': '세이브 횟수',
u'saved_count': '세이브 된 횟수',
u'play_count_short': '플레이',
u'clear_count_short': '클리어',
u'save_count_short': 'SAVE',
u'saved_count_short': 'SAVED',
u'excellent': '엑설런트',
u'excellent_count': '엑설런트 횟수',
u'excellent_tune_count': '엑설런트 곡 수',
u'fullcombo': '풀콤보',
u'fullcombo_count': '풀콤보 횟수',
u'fullcombo_tune_count': '풀콤보 곡 수',
u'counts': '횟수',
u'tunes': '곡수',
u'matched_player_count': '대전 횟수',
u'matched_victory_count': '대전 승리 횟수',
u'matched_victory_rate': '대전 승률',
u'matched_player_count_short': '대전',
u'matched_victory_count_short': '승리',
u'matched_victory_percent': '대전 승률',
u'marker': '마커',
u'background': '배경',
u'timestamp': '갱신 시간',
u'addiction': '중독율',

u'History': '곡별 기록',
u'History for %s': '%s 기록',
u'Statistics for All Users': '모든 사용자 통계',
u'%d-users': '총 %d 사용자',
u'stats-key': '이름',
u'stats-count': '사용자 수',
u'stats-total': '합계',

u'Toolbox': '추가 기능',
u'raw-files': '원본 데이터 파일',
u'raw-main': '메인페이지',
u'raw-score': '점수페이지',
u'raw-warning': '사용에 주의하세요!',
u'raw-warning-jubegraph': '이 파일들을 %s에 넣을 수 있긴 하지만, JubeatInfo는 Jubegraph가 이 데이터 파일을 제대로 처리하는지에 대한 어떤 보장도 하지 않습니다.',
u'raw-warning-recommendation': '가급적이면 본인 자신의 이어뮤즈먼트 패스를 사용해서 갱신하는 게 좋습니다.',
u'Jubegraph': 'Jubegraph',

u'err_no_alias': '사용자 이름이 주어지지 않았습니다.',
u'err_invalid_alias': '입력한 사용자 이름은 서비스에 등록되어 있지 않습니다. 올바른 사용자 이름으로 재시도하거나 서비스에 먼저 등록해 주세요.',

u'err_enroll_no_friend_id': '프렌드ID를 입력해주세요. 프렌드ID는 이어뮤즈먼트 웹사이트에서 확인하실 수 있습니다.',
u'err_enroll_friend_id_knit': '올바른 유비트 니트 프렌드ID가 아닙니다. 바른 ID로 재시도해주세요.',
u'err_enroll_duplicate': '이미 등록된 사용자 이름이나 프렌드ID입니다.',
u'err_enroll_duplicated_friend_id': '이미 등록된 프렌드ID입니다. 등록했던 사용자 이름을 확인해 보세요.',
u'err_enroll_duplicated_alias': '이미 등록된 사용자 이름입니다. 다른 이름으로 등록해 주세요.',

u'err_request_no_alias': '사용자 이름이 주어지지 않았습니다. 프렌드ID와 연결할 사용자 이름을 입력해 주세요.',
u'err_request_update_average': '특수 사용자의 갱신을 요청할 수 없습니다.',
u'err_forbidden': '잘못된 접근입니다.',

u'err_data_not_collected': '아직 데이터를 수집하지 못했습니다. 다음 업데이트 시간을 기다려주세요.',
u'err_eamusement_system': 'e-AMUSEMENT PASS 시스템 에러로 업데이트에 실패했습니다. 보통 잘못된 프렌드ID를 입력했을때 발생하게 됩니다. 프렌드ID가 올바르다면 갱신 요청 버튼을 누른 후 다음 업데이트를 기다려 주세요.',
u'err_eamusement_nonpublic': 'e-AMUSEMENT PASS를 아직 공개로 설정하지 않았습니다. 정보 공개 설정 후 갱신 요청 버튼을 눌러주세요.',
}

contents = {
# markers
u'ニット': '니트',
u'サイバー': '사이버',
u'フラワー': '꽃',
u'アフロ': '아프로',
u'シャッター': '셔터',
#$__l10n['ブルーリング': 'Blue Ring',
u'花火': '불꽃놀이',
u'ターゲット': '타겟',
u'たまご': '달걀',
u'火山': '화산',
u'ゲージ': '게이지',
u'オコジョ': '담비',
u'アイス': '얼음',
u'シャボン玉': '비누방울',
u'デジタルブロック': '디지털 블럭',
#$__l10n['サンドアート': 'Sand Art',
u'ミラーボール': '미러볼',
u'リプルズ': '리플즈',
#$__l10n['ユビ子': 
u'触': '촉(触)',
u'バナナ': '바나나',
#$__l10n['ブラー': 
u'絵画': '회화',
u'トーラス': '토러스',
u'襖': '미닫이',
u'ステルス': '스텔스',
u'色彩構成': '색채구성',
u'ねんごろねこ': '인사하는 고양이',
u'ストップウォッチ': '스탑 워치',
#$__l10n['コンシェルジュ': 'Concierge',
u'jubeatくん': '유비트군',

# backgrounds
u'グリーン': '초록',
u'ブルー': '파랑',
u'レモン': '노랑',
u'ダーク': '회색',

# locations
u'大韓民国': '대한민국',
u'未設定': '미설정',
u'香川県': '일본 가가와현',
u'鹿児島県': '일본 가고시마현',
u'神奈川県': '일본 가나가와현',
u'高知県': '일본 고치현',
u'京都府': '일본 교토부',
u'熊本県': '일본 구마모토현',
u'群馬県': '일본 군마현',
u'岐阜県': '일본 기후현',
u'長野県': '일본 나가노현',
u'長崎県': '일본 나가사키현',
u'奈良県': '일본 나라현',
u'新潟県': '일본 니가타현',
u'富山県': '일본 도야마현',
u'栃木県': '일본 도치기현',
u'東京都': '일본 도쿄도',
u'徳島県': '일본 도쿠시마현',
u'鳥取県': '일본 돗토리현',
u'宮城県': '일본 미야기현',
u'宮崎県': '일본 미야자키현',
u'三重県': '일본 미에현',
u'佐賀県': '일본 사가현',
u'埼玉県': '일본 사이타마현',
u'滋賀県': '일본 시가현',
u'静岡県': '일본 시즈오카현',
u'青森県': '일본 아오모리현',
u'愛知県': '일본 아이치현',
u'秋田県': '일본 아키타현',
u'山形県': '일본 야마가타현',
u'山口県': '일본 야마구치현',
u'山梨県': '일본 야마나시현',
u'愛媛県': '일본 에히메현',
u'大阪府': '일본 오사카부',
u'大分県': '일본 오이타현',
u'岡山県': '일본 오카야마현',
u'沖縄県': '일본 오키나와현',
u'和歌山県': '일본 와카야마현',
u'茨城県': '일본 이바라키현',
u'石川県': '일본 이시카와현',
u'岩手県': '일본 이와테현',
u'千葉県': '일본 지바현',
u'北海道': '일본 홋카이도',
u'兵庫県': '일본 효고현',
u'福島県': '일본 후쿠시마현',
u'福岡県': '일본 후쿠오카현',
u'福井県': '일본 후쿠이현',
u'広島県': '일본 히로시마현',
u'台湾': '타이완',
u'香港': '홍콩',
u'シンガポール': '싱가포르',
u'マカオ': '마카오',
}
