
# -*- coding: utf-8 -*-
messages = {
u'notice-ie6': '<p><strong>這網站不支援 Internet explorer 6</strong> 雖然IE7或IE8不完整,可是大部分正常標示.</p><p><strong>請使用比較完整的瀏覽器.</strong> .在這裡包括<a href="http://getfirefox.com">Mozilla Firefox 3.6+</a>, Google Chrome, Safari 4+等. <a href="/images/screenshot-firefox.png">請你參考下面的點數表.</a></p>',
u'notice-help': '<p>這網站還不完整,所以我們需要你們的幇忙.</p><p>如果幇忙網節目或网络設計,你會覺的使用方便.</p>',

u'select': '選擇',
u'select_user': '使用者選擇',
u'navigation_without_alias': '使用者選擇後個人項目單會活性.如果没有使用者,在下面加以登入.<br />如果要使用和Jubegraph同一的方式,兩個都輸入Friends ID.',

u'enroll_help': "'別名‘是在Jubeatinfo網站內部使用的名稱. 登入以後,用’別名‘能搜查你的情報資料. Friends ID是在Konami提供的個人識別號碼. 你能在e-Amusement service確認.",

u'ripples-app-desc': 'iPhone JubeatInfo 應用',
u'knit-service-beta-desc': '試驗中的service',
u'knit-service-developing-desc': '開發中的service',
u'knit-massda-desc': 'Jubegraph 更新文件下載',
u'knit-humanreadable-desc': '提供遊戲資料換成簡單的形式',
u'knit-statistics-desc': '遊戲資料統計分析',
u'knit-statistics-adv-desc': '提供多樣的遊戲資料分析換成更方便的分界面',
u'knit-mobileweb-desc': '流動網',
u'knit-iphoneapp-desc': 'iPhone JubeatInfo 應用 (一部機能可用)',
u'policy': '運營政策',
u'policy-update': '更新間隔: 没有更新要請, 最後更新後24+時間/有更新要請, 30分內(05-08時除外)',
u'policy-update-notice': '下次更新週期資料會更新. 需要更新週期, 參考更新政策.',
u'policy-unstable': 'service還不完整. 無豫告可引起service暂停或資料消失.',
u'policy-deny': '如果要使用service, 在計定上設定“情報公開”才可以使用. 没設定“情報公開”的計定自動會變成非活性而且在自動更新對象被除名. 要重新包含自動更新, 計定上設定“情報公開”然後按“更新要請”.',

u'FAQ': 'FAQ',
u'faq-user-from-japan-question': 'Why not users in Japan?',
u'faq-user-from-japan-answer': 'You can buy e-AMUSEMENT PASS in Japan. Please use Jubegraph rather than JubeatInfo, if available.',
u'faq-more-information-question': 'Why don\' you provide more informations? (like Play Count, No Gray, All Yellow, Full combo etc)',
u'faq-more-information-answer': 'We have technical limitation to aggregate play data. We do not hide any collected or collectable informations. We cannot do more.',

u'disclaimer': '免責项目: 3rddev是爲JubeatInfo组經營service. 所有權利及義務是JubeatInfo组包含. 住在日本時不能使用這service, 在日本使用這service時發生的所有法律要自己負責.',
u'user-agreement': 'User agreement: Every user should pray new record of developer team whenever using this service :p',
u'support': '顧客支援',

u'enroll-success': 'JubeatInfo service登入完了.',
u'request-accepted': '收取更新要求.',

u'alias': '外号',
u'enroll': '登入',
u'main_page': '首頁',
u'request_update': '更新要求',
u'massda': 'Jubegraph',
u'update': '%s用文件夾',
u'raw-files': '原本頁',
u'raw-main': '主頁',
u'raw-score': '比分頁',
u'raw-warning': '注意:',
u'raw-warning-jubegraph': 'While these files can be used for <a href="http://jubegraph.dyndns.org/jubeat_knit/user/24400021278396/">Jubegraph</a>, we do not guarantee that Jubegraph will parse and process them correctly.',
u'raw-warning-recommendation': 'It is best to use your own E-Amusement Pass to get them instead.',
u'average_score': '看平均分數',
u'statistics-tbs': 'TBS顺次',
u'my_page': '看我的帳戶',
u'toolbox': '額外的功能',

u'music-total': '合算比分',
u'music-average': '平均比分',

u'difftool': '比較用具',
u'no_compare': '平均者比較',
u'compare_rival': '和其他使用者比較',
u'swap_rival': 'See this page at the view of this user',
u'compare_date': '特定日期比較',
u'before-date': '以前',
u'after-date': '以後',
u'now-date': '現在',
u'diff': '比較',

u'statistics': '統計',
u'grade_bsc': 'BSC',
u'grade_adv': 'ADV',
u'grade_ext': 'EXT',
u'grade_tot': 'TOT',

u'scoreboard': '曲別分數',
u'scoremode': '分數標示方法',
u'raw_score': '基本分數',
u'raw_score_from_exc': '達到EXCELLENT的分數',
u'scaled_score': '換算分數',
u'scaled_score_desc': '這是達到EXCELLENT之前的換算分數. 0.0是EXCELLENT, 達成 full gauge時 Great/Good/Miss 各減分0.3/0.6/1.0分. 如果没有達成 full gauge時, 數字不能簡單掉落, 所以這只是參考用分數.',
u'tracktitle': '題目',
u'order-version': '版本+遊戲內順序',
u'order-title': '題目',
u'order-sort_id': '遊戲內順序',
u'order-score': '分數',
u'order-level': '難度',
u'order-notes': 'note數',
u'order-date': '更新日',
u'order-diff': '差',
u'icon_avg': '平均',
u'icon_rival': '對手',
u'notes': 'note數',
u'title-average': '平均',
u'title-total': '合計',
u'emphasis-win': '勝利!',
u'emphasis-draw': '同點',
u'emphasis-new': '更新!',

u'rank': '顺次',
u'userstat': '基本帳戶',
u'as-of-%s': '%s現在',
u'friend_id': 'Friend ID',
u'card_name': '卡名',
u'title': '稱號',
u'group_name': '集團',
u'no-group': '無所屬',
u'last_play': '最近遊戲',
u'last_location': '最近遊戲地區',
u'last_date': '最近遊戲日期',
u'jubility': 'Jubility',
u'jubility_diff_short': '和之前差異',
u'achievement_point': '成果分數',
u'achievement_rank': '成果分數顺次',
u'play_count': '遊戲次數',
u'clear_count': 'Clear次數',
u'save_count': 'Save次數',
u'saved_count': 'Saved次數',
u'play_count_short': '遊戲',
u'clear_count_short': 'Clear',
u'save_count_short': 'SAVE',
u'saved_count_short': 'SAVED',
u'excellent': 'Excellent',
u'excellent_count': 'Excellent次數',
u'excellent_tune_count': 'Excellent曲數',
u'fullcombo': 'FullCombo',
u'fullcombo_count': 'FullCombo次數',
u'fullcombo_tune_count': 'FullCombo曲數',
u'counts': '次數',
u'tunes': '曲數',
u'matched_player_count': '對戰次數',
u'matched_victory_count': '對戰勝力次數',
u'matched_victory_rate': '對戰勝率',
u'matched_player_count_short': '對戰',
u'matched_victory_count_short': '勝力',
u'matched_victory_percent': '對戰勝率',
u'marker': 'Marker',
u'background': '背景',
u'timestamp': '更新時間',
u'addiction': '依存度',

u'History': '曲履歷',
u'History for %s': '%s 記錄',
u'Statistics for All Users': 'Stastistics for All Users',
u'tbs-user-count': 'Total %d Users',

u'err_invalid_alias': '按錯別名. 請按正確別名或先登入別名後使用.',

u'err_enroll_no_friend_id': '請輸入Friend ID. Friend ID可在e-Amusement網站確認.',
u'err_enroll_friend_id_knit': '這不是正確Friend ID. 請你按正確ID.',
u'err_enroll_duplicate': '以經登入完壁的使用者別名或Friend ID.',
u'err_enroll_duplicated_friend_id': '以經登入完壁的Friend ID.',
u'err_enroll_duplicated_alias': '以經登入完壁的使用者別名.',

u'err_request_no_alias': 'No given alias. 請你輸入和Friend ID連接的使用者別名.',
u'err_request_update_average': '不能要求特殊使用者的更新.',
u'err_forbidden': '接近錯誤.',

u'err_data_not_collected': 'JubeatInfo did not collected your data yet. Please wait next minor update time slot.',
u'err_eamusement_system': 'JubeatInfo meets e-AMUSEMENT system error. It usually caused by wrong Friend ID. If not, click request update button and wait next update.',
u'err_eamusement_nonpublic': 'You did not set your e-AMUSEMENT PASS as public yet. Please set it public and click request update button.',
}
contents = {
# markers
u'ニット': 'Knit',
u'サイバー': 'Cyber',
u'フラワー': 'Flower',
u'アフロ': 'Afro',
u'シャッター': 'Shutter',
u'ブルーリング': 'Blue Ring',
#$__l10n['花火': 'Fireworks',
u'ターゲット': 'Target',
u'たまご': 'Egg',
#$__l10n['火山': 'Volcano',
u'ゲージ': 'Gage',
u'オコジョ': 'Stoat',
u'アイス': 'Ice',
u'シャボン玉': 'Bubble',
u'デジタルブロック': 'Digital Block',
u'サンドアート': 'Sand Art',
u'ミラーボール': 'Mirror Ball',
u'リプルズ': 'Ripples',
#$__l10n['ユビ子': 
#$__l10n['触': 'Touch',
u'バナナ': 'Banana',
#$__l10n['ブラー': 
#$__l10n['絵画': 'Painting',
u'トーラス': 'Torus',
#$__l10n['襖': 'Sliding'; // Sliding Door
u'ステルス': 'Stealth',
#$__l10n['色彩構成': ''; // Color construction
u'ねんごろねこ': 'Polite Cat',
u'ストップウォッチ': 'Stop Watch',
u'コンシェルジュ': 'Concierge',
#$__l10n['jubeatくん': 'Jubeat',

# backgrounds
u'グリーン': '綠',
u'ブルー': '請',
u'レモン': '黃',
u'ダーク': '暗',

# locations
#$__l10n['愛知県': 'Aichi, Japan',
#$__l10n['秋田県': 'Akita, Japan',
#$__l10n['青森県': 'Aomori, Japan',
#$__l10n['千葉県': 'Chiba, Japan',
#$__l10n['愛媛県': 'Ehime, Japan',
#$__l10n['福井県': 'Fukui, Japan',
#$__l10n['福岡県': 'Fukuoka, Japan',
#$__l10n['福島県': 'Fukushima, Japan',
#$__l10n['岐阜県': 'Gifu, Japan',
#$__l10n['群馬県': 'Gunma, Japan',
#$__l10n['広島県': 'Hiroshima, Japan',
#$__l10n['北海道': 'Hokkaido, Japan',
u'香港': '香港',
#$__l10n['兵庫県': 'Hyogo, Japan',
#$__l10n['茨城県': 'Ibaraki, Japan',
#$__l10n['石川県': 'Ishikawa, Japan',
#$__l10n['岩手県': 'Iwate, Japan',
#$__l10n['香川県': 'Kagawa, Japan',
#$__l10n['鹿児島県': 'Kagoshima, Japan',
#$__l10n['神奈川県': 'Kanagawa, Japan',
#$__l10n['高知県': 'Kochi, Japan',
#$__l10n['大韓民国': 'Korea',
u'대한민국': '大韓民国',
#$__l10n['熊本県': 'Kumamoto, Japan',
#$__l10n['京都府': 'Kyoto, Japan',
#$__l10n['三重県': 'Mie, Japan',
#$__l10n['宮城県': 'Miyagi, Japan',
#$__l10n['宮崎県': 'Miyazaki, Japan',
#$__l10n['未設定': 'N/A',
#$__l10n['長野県': 'Nagano, Japan',
#$__l10n['長崎県': 'Nagasaki, Japan',
#$__l10n['奈良県': 'Nara, Japan',
#$__l10n['新潟県': 'Niigata, Japan',
#$__l10n['大分県': 'Oita, Japan',
#$__l10n['岡山県': 'Okayama, Japan',
#$__l10n['沖縄県': 'Okinawa, Japan',
#$__l10n['大阪府': 'Osaka, Japan',
#$__l10n['佐賀県': 'Saga, Japan',
#$__l10n['埼玉県': 'Saitama, Japan',
#$__l10n['滋賀県': 'Shiga, Japan',
#$__l10n['静岡県': 'Shizuoka, Japan',
u'台湾': '台灣',
#$__l10n['栃木県': 'Tochigi, Japan',
#$__l10n['徳島県': 'Tokushima, Japan',
#$__l10n['東京都': 'Tokyo, Japan',
#$__l10n['鳥取県': 'Tottori, Japan',
#$__l10n['富山県': 'Toyama, Japan',
#$__l10n['和歌山県': 'Wakayama, Japan',
#$__l10n['山形県': 'Yamagata, Japan',
#$__l10n['山口県': 'Yamaguchi, Japan',
#$__l10n['山梨県': 'Yamanashi, Japan',
u'シンガポール': '新加坡',
u'マカオ': '澳門',
}
